### ISSUE TITLE
Error: Cannot find module '@csstools/normalize.css'

### ISSUE THREAD

**Issue by manuelbieh** [csstools/postcss-normalize#40]
That's closely related to this (locked) issue here: https://github.com/facebook/create-react-app/issues/6886

With the difference that I'm not using create-react-app but a custom setup (that is somewhat similar to CRA) and I'm still getting this error after upgrading from 7.0.1 to 8.0.0. I've already removed node_modules and re-installed everything again as it was suggested in the other issue but it's still not working with the same error: `Cannot find module '@csstools/normalize.css'`.

Can be reproduced by cloning [this repo](https://github.com/manuelbieh/react-ssr-setup), upgrading postcss-normalize to 8.0.0 and then running `yarn start`.

Any idea what else I have to change to make postcss and postcss-loader find the normalize.css file?

**Comment by jonathantneal** [comment]
I don’t yet know what is causing the error for you, but I suspect it has something to do with module paths. The most likely point of failure could be:

1. This package uses Node’s internal `Module._resolveFilename` to identify the package. This is a technique I have seen used in other packages with success ([source](https://github.com/csstools/postcss-normalize/blob/master/src/lib/cssMap.js#L41-L48)).
2. This package uses a combination of ES5/ES6 methods to resolve the current filename ([source](https://github.com/csstools/postcss-normalize/blob/master/src/lib/cssMap.js#L7-L9)). You can compare that with how it compiles into the [CommonJS implementation](https://unpkg.com/postcss-normalize@8.0.0/index.cjs.js) and the [Modules implementation](https://unpkg.com/postcss-normalize@8.0.0/index.esm.mjs) versions.

I don’t see an issue in the source I have shared with you, however, I would suspect that is where the issue is coming from. If you think there are other people who can help, please feel free to show them this source code, as I think it has the highest likelihood of being the culprit.

**Comment by manuelbieh** [comment]
Thanks for the links, I will have a look!

**Comment by Foxxtail1** [comment]
Reverting to 7.0.1 still results in the same issue. Even after clearing node_modules.

**Comment by bnguyensn** [comment]
In my case, this was a Windows path issue as everything worked fine on my MacOS machine. I was using this as a webpack plugin as well.

The issue was that, in Windows, [this line](https://github.com/csstools/postcss-normalize/blob/master/src/lib/cssMap.js#L46) produced paths with duplicate drive letters like below, preventing correct module resolution:
![image](https://user-images.githubusercontent.com/17515009/59152719-d3a7af00-8a41-11e9-93b9-cf1b49591c9d.png)

In my app, I was able to fix this using Node's [url.fileURLToPath()](https://nodejs.org/api/url.html#url_url_fileurltopath_url) for the variable `currentDirname` like so (also be aware that `url.fileURLToPath` is only available in Node > 10.12.0):
```javascript
// node_modules/postcss-normalize/index.cjs.js
// ...
const currentDirname = path.dirname(currentFilename); // Before
const currentDirname = path.dirname(url.fileURLToPath(currentURL)); // After
```

After that update, things worked out fine for me.

I suppose to fix this issue, one can update the variable `currentDirname` at the [source](https://github.com/csstools/postcss-normalize/blob/master/src/lib/cssMap.js#L9) like the above? But I'm not entirely sure if this is the correct fix yet as I'm not well-versed on this change's implications on ESM use cases, and this function requires a pretty recent Node version. Writing this here because it might help some others for now though!

**Comment by jonathantneal** [comment]
Thanks to your sleuthing, @bnguyensn, I think I was able to find the problem and resolve it by using the legacy `__filename` in CJS environments. This has been published in v8.0.1. Please let me know if anyone has further issues and I will reopen this issue.

Thank you again for the feedback. I would have never found it without all of your input.

**Comment by jonaskuske** [comment]
Had the same issue when using it in Vue CLI and the proposed `.fileURLtoPath()` fix didn't work either, maybe because I'm using WSL.
8.0.1 fixed it, thank you 🎉

**Comment by seshangamage** [comment]
Had the same did the below to solve

Uninstall package

 npm remove csstools/normalize.css

After that, we have to install again

 npm install csstools/normalize.css

**Comment by lucasjinreal** [comment]
```
npm install csstools/normalize.css


npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit  csstools/normalize.css resetting remote /home/jintian/.npm/_git-remotes/git-github-com-csstools-normalize-css-git-4404ab96 because of error: { Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Socket.stream.socket.on (internal/child_process.js:346:11)
npm WARN addRemoteGit     at emitOne (events.js:116:13)
npm WARN addRemoteGit     at Socket.emit (events.js:211:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:567:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }

```

**Comment by ChetanGhediyaTA** [comment]
> Thanks to your sleuthing, @bnguyensn, I think I was able to find the problem and resolve it by using the legacy `__filename` in CJS environments. This has been published in v8.0.1. Please let me know if anyone has further issues and I will reopen this issue.
> 
> Thank you again for the feedback. I would have never found it without all of your input.

I am facing the problem of '@csstools/normalize.css' any idea?

**Comment by eliasaj92** [comment]
If it helps anyone ( @ChetanGhediyaTA ) :

update npm globally: `sudo npm install npm@latest -g`
check npm version: `npm -v` should be 6.13.0 or higher. If not, do `hash -r` then check the version again
clean cache: `npm cache clean --force` use `sudo` or whatever if you come across a privilege issue
reinstall node modules: `rm -rf node_modules` then `npm install`

This is how I got `npm run build` working again after facing this issue

**Comment by IAluI** [comment]
@jonathantneal 
I have this issue in the following environment
- windows 10
- node 18.12.1

Replace
`const currentFilename = new URL(currentURL).pathname;`
to
`const currentFilename = fileURLToPath(currentURL);`
in this [line](https://github.com/csstools/postcss-normalize/blob/f690d6ab9bbc35b51be28706a84d53a88761e179/src/lib/cssMap.js#L8) solve this problem. Like was suggested in this [comment](https://github.com/csstools/postcss-normalize/issues/40#issuecomment-500171342). This work on windows 10 and ubuntu 20.04. It's bad solution?

How i can help fix this bug? Pull request?

**Comment by annshiv** [comment]
> > Thanks to your sleuthing, @bnguyensn, I think I was able to find the problem and resolve it by using the legacy `__filename` in CJS environments. This has been published in v8.0.1. Please let me know if anyone has further issues and I will reopen this issue.
> > Thank you again for the feedback. I would have never found it without all of your input.
> 
> I am facing the problem of '@csstools/normalize.css' any idea?

try `npm i normalize-css`

**Comment by jenschr** [comment]
I too have this problem and `npm i normalize-css` does not solve the problem. The script is already installed, but the referenced script is removed from https://www.npmjs.com/package/csstools so I gues it contained malware or something else? Any hints on how to solve this would be much appreciated!

I'm setting up a React app on Ubuntu 22.04. I'm using NodeJS v18.13.0. This is the errror I'm getting:

```
> frontend@0.1.0 build:prod
> npm install -g env-cmd && env-cmd -f .env react-scripts build


changed 8 packages, and audited 9 packages in 2s

found 0 vulnerabilities
Creating an optimized production build...
Failed to compile.

Loading PostCSS "postcss-normalize" plugin failed: Cannot find module '@csstools/normalize.css'
Require stack:
- /root/frontend/node_modules/postcss-normalize/index.cjs

(@/root/frontend/src/App.css)
```

I get the error when running the build:prod command. Here is my quite standard package.json file:

```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "env-cmd": "^10.1.0",
    "mqtt": "^4.3.7",
    "normalize-css": "^2.3.1",
    "react": "^18.2.0",
    "react-audio-player": "^0.17.0",
    "react-custom-scroll": "^5.0.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.11.0",
    "react-router-dom": "^6.16.0",
    "react-scripts": "^5.0.1",
    "web-vitals": "^2.1.4",
    "wouter": "^2.11.0"
  },
  "scripts": {
    "start": "env-cmd -f .env.dev react-scripts start",
    "start:prod": "env-cmd -f .env react-scripts start",
    "build:prod": "npm install -g env-cmd && env-cmd -f .env react-scripts build",
    "build:dev": "env-cmd -f .env react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "dotenv-webpack": "^8.0.1"
  }
}
```
